[profile.default]
src = 'contracts'
out = "out"
libs = ["lib"]
tests = 'tests/foundry'

via_ir = true

[rpc_endpoints]
testnet = "${DEVNET_RPC_URL}"

#[etherscan]
#testnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
